name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --prefer-offline

    - name: Check for test script
      id: check-test-script
      run: |
        if npm run | grep -q "test"; then
          echo "has-test-script=true" >> $GITHUB_OUTPUT
        else
          echo "has-test-script=false" >> $GITHUB_OUTPUT
        fi

    - name: Run tests
      if: steps.check-test-script.outputs.has-test-script == 'true'
      run: |
        mkdir -p test-results
        npm test -- --reporter mocha-junit-reporter --reporter-options mochaFile=test-results/results.xml

    - name: Warn if no tests are defined
      if: steps.check-test-script.outputs.has-test-script == 'false'
      run: |
        echo "::warning::No test script found in package.json. Consider adding tests to ensure code quality."
        echo "To add a basic test script, include this in your package.json:"
        echo '{
          "scripts": {
            "test": "echo \"No tests specified\" && exit 0"
          }
        }'
        exit 0

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always() && steps.check-test-script.outputs.has-test-script == 'true'
      with:
        name: test-results
        path: test-results/results.xml

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --prefer-offline --production

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Application
      env:
        REMOTE_USER: ${{ secrets.SSH_USER }}
        SERVER_IP: ${{ secrets.SSH_HOST }}
        APP_PATH: ${{ secrets.APP_PATH }}
      run: |
        # Validate environment variables
        if [ -z "$REMOTE_USER" ] || [ -z "$SERVER_IP" ] || [ -z "$APP_PATH" ]; then
          echo "Missing required environment variables"
          exit 1
        fi

        # Create deployment script
        DEPLOY_SCRIPT=$(mktemp)
        cat << 'EOF' > $DEPLOY_SCRIPT
        #!/bin/bash
        set -euo pipefail
        cd $APP_PATH
        git fetch origin main
        git reset --hard origin/main
        npm ci --prefer-offline --production
        pm2 reload ecosystem.config.js --env production
        EOF

        # Execute deployment
        scp -o StrictHostKeyChecking=no $DEPLOY_SCRIPT ${REMOTE_USER}@${SERVER_IP}:/tmp/deploy.sh
        ssh -o StrictHostKeyChecking=no ${REMOTE_USER}@${SERVER_IP} \
          "chmod +x /tmp/deploy.sh && /tmp/deploy.sh && rm /tmp/deploy.sh"